### ISSUE TITLE
Hi! Fan of your work!

### ISSUE THREAD

**Issue by jjensn** [zyantific/zyan-hook-engine#1]
Hey, this looks like an interesting project from the README. Would be interested in seeing how far you got with it.

**Comment by flobernd** [comment]
Hi, thanks for your interest. You might want to take a look at the [develop-branch](/zyantific/zyan-hook-engine/tree/develop). I didn't commit for quite a long time, but I will continue this project, after the [Zydis](/zyantific/zyan-disassembler-engine/tree/develop) rewrite is done.
