### ISSUE TITLE
file not be found?where

### ISSUE THREAD

**Issue by ddkwork** [zyantific/zyan-hook-engine#2]
file not be found?where is ZyrexExportConfig.h?

**Comment by ddkwork** [comment]
ZyrexTransactionBegin();
	// .......some hook code?
    ZyrexTransactionAbort();

![image](https://user-images.githubusercontent.com/19886504/48743871-ede58f80-ec9f-11e8-9b46-f52a6134fe57.png)

**Comment by flobernd** [comment]
WiP (= work in progress) means that the project is not finished yet. The `ZycrexConfig.h` is automatically generated by CMake. You might be able to compile the project using CMake, but it won't work anyways.
