### ISSUE TITLE
undefined "ZyrexTrampoline" in examples

### ISSUE THREAD

**Issue by nblog** [zyantific/zyan-hook-engine#3]
I found in the process of using "examples"
Function has an undefined type "ZyrexTrampoline"

[examples/InlineHook.c #L81](https://github.com/zyantific/zyan-hook-engine/blob/master/examples/InlineHook.c#L81) "ZyrexTrampoline trampoline;"

I tried looking elsewhere and it didn't work.

hope to be helped, thanks.

**Comment by flobernd** [comment]
Hi there, this project is still work in progress. The example currently is more like a test project for myself during development.

I'm actively working on the Transaction API (aka. the public interface) and will push a working version within the next weeks.
